version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: expense-tracker-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: expense_tracker
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - expense-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U expense_user -d expense_tracker"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Expense Tracker Application
  expense-tracker:
    image: com.expense.tracker/expense-tracker:1.0-SNAPSHOT
    container_name: expense-tracker-app
    restart: unless-stopped
    ports:
      - "9000:9001"
    environment:
      DATABASE_URL: r2dbc:postgresql://postgres:5432/expense_tracker
      DATABASE__USERNAME: user
      DATABASE__PASSWORD: password
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - expense-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s


volumes:
  postgres_data:
    driver: local

networks:
  expense-network:
    driver: bridge
