spring:
  application:
    name: expense-tracker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/.well-known/jwks.json
  r2dbc:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    pool:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: ${FLYWAY_URL}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    baseline-on-migrate: true
    validate-on-migrate: true
server:
  port: 9000
management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: info, health, metrics
  endpoint:
    metrics:
      enabled: ${DD_ENABLED:true}
  statsd:
    metrics:
      export:
        enabled: true
        host: ${DD_AGENT_HOST:/var/run/datadog/dsd.socket}
        protocol: ${DD_AGENT_PROTOCOL:uds_datagram}
        max-packet-length: ${DD_AGENT_MAX_PACKET_LENGTH:8192}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

# JWT Configuration
app:
  jwt:
    expiration: ${JWT_EXPIRATION:3600}  # 1 hour in seconds
    issuer: ${JWT_ISSUER:expense-tracker}

info:
  app:
    name: Expense Tracker
    description: A simple expense tracking and analytics application
    java: ${java.specification.version}